# -*- coding: utf-8 -*- 
# Generated by xuhao on 2020/11/8 11:48

class MGraph(object):

    def __init__(self):
        self.Vex=[]     # 存储各个顶点,一维数组
        self.Edge=[[]]    # 存储各个顶点之间的连接关系，二维数组
        self.vexnum=0   # 顶点树
        self.arcnum=0   # 边数



