# -*- coding: utf-8 -*- 
# Generated by xuhao on 2020/11/8 15:47

class ArcNode(object):
    """
    边表节点
    """
    def __init__(self):
        self.adjvex=None
        self.next=None

class VNode(object):
    """
    顶点表节点
    """
    def __init__(self):
        self.data=None
        self.first=None

class ALGraph(object):
    """
    ALGraph是以邻接表存储的图类型
    """
    def __init__(self):
        self.vertices=[]
        self.vexnum=0
        self.arcnum=0
