# -*- coding: utf-8 -*- 
# Generated by xuhao on 2020/11/9 13:20
"""
折半插入排序
"""

def insertSort(A:list)->None:
    new_A=[None]+A
    i,n=2,len(A)
    while i<=n:
        new_A[0]=new_A[i]
        low,high=1,i-1
        while low<=high:
            mid=int((low+high)/2)
            if new_A[mid]>new_A[0]:
                high=mid-1
            else:
                low=mid+1
        j=i-1
        while j>=high+1:
            new_A[j+1]=new_A[j]
            j-=1
        new_A[high+1]=new_A[0]
        i+=1
    return new_A[1:]


if __name__=="__main__":
    print(insertSort([3,2,1,4,5]))

