# -*- coding: utf-8 -*- 
# Generated by xuhao on 2020/11/9 13:20
"""
希尔排序
"""

def shellSort(A:list)->list:
    new_A=[None]+A
    n=len(A)
    dk=int(n/2)
    while dk>=1:
        i=dk+1
        while i<=n:
            if new_A[i]<new_A[i-dk]:
                new_A[0]=new_A[i]
                j=i-dk
                while j>0 and new_A[0]<new_A[j]:
                    new_A[j+dk]=new_A[j]
                    j-=dk
                new_A[j+dk]=new_A[0]
            i+=1
        dk=int(dk/2)
    return new_A[1:]


if __name__=="__main__":
    print(shellSort([2,1,4,5,3]))


