# -*- coding: utf-8 -*- 
# Generated by xuhao on 2020/11/9 13:19

"""
直接插入排序
"""

def insertSort(A:list)->None:
    new_A=[None]+A
    i,n=2,len(A)
    while i<=n:
        if new_A[i]<new_A[i-1]:
            j,new_A[0]=i-1,new_A[i]
            while new_A[j]>new_A[0]:
                new_A[j+1]=new_A[j]
                j-=1
            new_A[j+1]=new_A[0]
        i+=1
    print(new_A[1:])


if __name__=="__main__":
    insertSort([2,1,5,4,3])
