# -*- coding: utf-8 -*- 
# Generated by xuhao on 2020/11/7 22:58

class Node(object):
    def __init__(self,data,leftChild=None,rightChild=None):
        self.data=data
        self.leftChild=leftChild
        self.rightChild=rightChild

class BSTInsert(object):

    def bst_insert(self,T:Node,key:int)->int:
        """
        二叉排序树插入操作
        :param T:
        :param key:
        :return:
        """
        if T is None:
            T=Node(data=key)
            T.leftChild=T.rightChild=None
        elif key==T.data:
            return 0
        elif key<T.data:
            return BSTInsert().bst_insert(T.leftChild,key)
        else:
            return BSTInsert().bst_insert(T.rightChild.key)